name: 'food_price_tracker'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipython=8.17.2
  - ipykernel=6.26.0
  - jupyterlab=4.0.9
  - pandas=2.2
  - altair=5.3
  - vl-convert-python=1.3.0
  - vegafusion=1.6.6
  - vegafusion-jupyter=1.6.6
  - dash=2.16
  - dash-bootstrap-components=1.5
  - dash-daq=0.5
  - dash-vega-components=0.9
  - country_converter=1.2
  - pip=24.0
  - pip: 
    - hdx-python-api==6.2.6
