name: 'food_price_tracker'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipython=8.17.2
  - ipykernel=6.26.0
  - jupyterlab=4.0.9
  - pandas=2.1.3
  - altair=5.1.2
  - vl-convert-python=1.1.0
  - vegafusion=1.4.5
  - vegafusion-jupyter=1.4.5
  - dash=2.16
  - dash_bootstrap_components=1.5
  - dash-daq=0.5
